### ISSUE TITLE
Use enum Character::A to prevent potential bug

### ISSUE THREAD

**Issue by idanai** [Hydrantz/leds_screen#1]
https://github.com/Hydrantz/leds_screen/blob/ecb04db1f418f8a53b3cf7bc24c0974fc2250803/arduino/scoreboard.cpp#L124

In the function Scoreboard::char_to_index(..):
using 10 instead of the enum's value itself (Character::A) may pose a bug if you ever decide to reorder the enum's values.

Solution:
`return chr - 'A' + (int)Character::A;`

**Comment by Hydrantz** [comment]
issue fixed in 136535a

**Comment by Hydrantz** [comment]
issue fixed in 136535a
